package com.PharmStock.entity;

import jakarta.persistence.*;

@Entity
@Table(name="`user`")
public class User {

    @Column(name="userId")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer userId;

    @Column(name="username")
    private String username;

    @Column(name="password")
    private String password;

    
    //default, no-arg constructor for Jackson ObjectMapper
    public User() {
    }

    
    //When posting new user, userId will be autogenerated
    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }


    //when retrieving user from database, need all args.
    public User(Integer userId, String username, String password) {
        this.userId = userId;
        this.username = username;
        this.password = password;
    }



    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    
    
}
